### ISSUE TITLE
Headless server has issues?

### ISSUE THREAD

**Issue by fire** [GammaGames/godocker#1]
What do you mean?

**Comment by GammaGames** [comment]
I can't find a way to export a project as a headless binary file to run, the only way I've found to run a headless version is to run the project directly by calling godot from within the project. Also the headless server's export has been broken for the past ~3 minor releases.

This is still very much a WIP too, I just put it on the reddit thread in case anyone wanted to see my server code.

**Comment by fire** [comment]
I was using master git (server) to export and it seemed to work for me:

Can you post errors?

**Comment by fire** [comment]
https://github.com/godotengine/godot/issues/18470 Reports something like that.

Do you know about https://github.com/godotengine/godot/issues/16779 ?

**Comment by fire** [comment]
```
git clone https://github.com/godotengine/godot.git -b 3.0
scons platform=server
scons platform=server tools=no target=release_debug bits=64
scons platform=server tools=no target=release_debug bits=64
# Modify export_presets.cfg to point to the path above
# Can use the editor.
# If your docker env is minimal
export HOME=`pwd`/..
mkdir -p $HOME/.local/share
mkdir -p $HOME/.config
mkdir -p $HOME/.cache
# end minimal
../godot/bin/godot_server.server.tools.64 --export "Linux X11" ../multiplayer_pong_godot
cd ..
./multiplayer_pong_godot
# It may not be obvious that the multiplayer_pong server is waiting for gui input
```

Just checked it and it seemed to export.

**Comment by GammaGames** [comment]
When I try to export I get:

```sh
ERROR: copy: Failed to open 
   At: core/os/dir_access.cpp:304.
ERROR: _fs_changed: Project export failed with error code 12.
   At: editor/editor_node.cpp:471.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
```

I am able to export using the 3.0.1 server, but when you run it it opens the game window.

**Comment by fire** [comment]
You don't have the templates setup, you must use custom debug and release templates.

**Comment by fire** [comment]
Error 12 is ERR_FILE_CANT_OPEN.

**Comment by fire** [comment]
Oops I misread, you can use dummy visual driver. "--video-driver dummy"

**Comment by GammaGames** [comment]
Where am I using that flag? I tried it when running the docker container (unknown flag), exporting (exported with window still) and running the exported file (crashed with `ERROR: _load: Method/Function Failed, returning: RES()`).

**Comment by GammaGames** [comment]
You can provide a pck file to the server to run an exported project, that is exactly what I was looking for.
